keys:
  - &nix-desktop 9F36F6D8FFE85CB8AF42592ACC597166004906B8
  - &nix-mac 1A72119AE19739F885BC45D4F9A15ABF961F623F

creation_rules:
  - path_regex: ^hosts/nix-desktop/secrets\.yaml$
    key_groups:
      - pgp:
          - *nix-desktop

  - path_regex: ^hosts/nix-desktop/tailscale\.sops\.json$
    key_groups:
      - pgp:
          - *nix-desktop

  - path_regex: ^hosts/nix-mac/secrets\.yaml$
    key_groups:
      - pgp:
          - *nix-mac
