;;; package-policy-tests.el --- Ownership regression checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'package)
(defvar nh-emacs-nix-package-names)
(defvar nh-emacs-nix-package-directory)
(defvar dotspacemacs-additional-packages)
(defvar dotspacemacs-frozen-packages)
(defvar go-use-golangci-lint)
(defvar go-backend)
(defvar lsp-diagnostics-provider :auto)
(defvar lsp-diagnostics-mode)
(let ((directory (file-name-directory load-file-name)))
  (load (expand-file-name "../package-policy.el" directory) t t)
  (load (expand-file-name "../.spacemacs" directory) nil t))

(ert-deftest nh-policy-preserves-unrelated-settings-and-is-idempotent ()
  (let ((nh-emacs-nix-package-names '(envrc vterm))
        (nh-emacs-nix-package-directory "/nix/test/elpa")
        (package-directory-list nil)
        (package-pinned-packages '((org . "gnu") (vterm . "melpa")))
        (dotspacemacs-additional-packages '(envrc (vterm :location elpa) logview))
        (dotspacemacs-frozen-packages '(org)))
    (nh/emacs-apply-nix-package-policy)
    (let ((settings (list dotspacemacs-additional-packages
                          dotspacemacs-frozen-packages package-pinned-packages)))
      (nh/emacs-apply-nix-package-policy)
      (should (equal settings (list dotspacemacs-additional-packages
                                   dotspacemacs-frozen-packages package-pinned-packages))))
    (should (equal dotspacemacs-additional-packages
                   '((envrc :location site) (vterm :location site) logview)))
    (should (member 'org dotspacemacs-frozen-packages))
    (should (equal (cdr (assq 'org package-pinned-packages)) "gnu"))
    (should (member "/nix/test/elpa" package-directory-list))))

(ert-deftest nh-policy-blocks-newer-archive-owned-dependency ()
  (let ((nh-emacs-nix-package-names '(vterm))
        (nh-emacs-nix-package-directory "/nix/test/elpa")
        (package-directory-list nil)
        (package-pinned-packages nil)
        (package-archive-contents nil)
        (package-alist (list (list 'vterm (package-desc-create
                                          :name 'vterm :version '(20260406 134)
                                          :dir "/nix/test/elpa/vterm" :reqs nil))))
        (dotspacemacs-additional-packages nil)
        (dotspacemacs-frozen-packages nil))
    (nh/emacs-apply-nix-package-policy)
    (package--add-to-archive-contents '(vterm . [(20990101) nil "new" single]) "melpa")
    (should-not (assq 'vterm package-archive-contents))
    (should-error (package-compute-transaction nil '((vterm (20990101)))))))

(ert-deftest nh-policy-clears-owned-candidates-from-an-already-loaded-archive ()
  (let ((nh-emacs-nix-package-names '(vterm))
        (nh-emacs-nix-package-directory "/nix/test/elpa")
        (package-directory-list nil)
        (package-pinned-packages nil)
        (package-archive-contents '((vterm cached-candidate) (magit unrelated-candidate)))
        (dotspacemacs-additional-packages nil)
        (dotspacemacs-frozen-packages nil))
    (nh/emacs-apply-nix-package-policy)
    (should-not (assq 'vterm package-archive-contents))
    (should (assq 'magit package-archive-contents))))

(ert-deftest nh-go-lint-selection-uses-current-buffer-environment ()
  (with-temp-buffer
    (setq-local go-use-golangci-lint t)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) nil)))
      (nh/emacs-go-lint-availability)
      (should-not go-use-golangci-lint))
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/project/bin/golangci-lint")))
      (nh/emacs-go-lint-availability)
      (should go-use-golangci-lint))))

(ert-deftest nh-shell-import-preserves-buffer-local-project-environment ()
  (let ((original-env (default-value 'process-environment))
        (original-path (default-value 'exec-path)))
    (unwind-protect
        (with-temp-buffer
          (setq-local process-environment '("PATH=/project/bin")
                      exec-path '("/project/bin"))
          (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                    ((symbol-function 'require) (lambda (&rest _) t))
                    ((symbol-function 'exec-path-from-shell-initialize)
                     (lambda ()
                       (setq process-environment '("PATH=/global/bin")
                             exec-path '("/global/bin")))))
            (nh/emacs-initialize-environment))
          (should (equal process-environment '("PATH=/project/bin")))
          (should (equal exec-path '("/project/bin")))
          (should (equal (default-value 'exec-path) '("/global/bin"))))
      (setq-default process-environment original-env exec-path original-path))))

(ert-deftest nh-shell-import-selects-the-global-shell-on-project-reload ()
  (let ((original-env (default-value 'process-environment)) selected)
    (unwind-protect
        (progn
          (setq-default process-environment '("SPACEMACS_SHELL=/global/bin/zsh"))
          (with-temp-buffer
            (setq-local process-environment '("SPACEMACS_SHELL=/project/bin/zsh"))
            (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                      ((symbol-function 'require) (lambda (&rest _) t))
                      ((symbol-function 'exec-path-from-shell-initialize)
                       (lambda () (setq selected exec-path-from-shell-shell-name))))
              (nh/emacs-initialize-environment))
            (should (equal selected "/global/bin/zsh"))))
      (setq-default process-environment original-env))))

(ert-deftest nh-go-diagnostics-recover-when-envrc-removes-the-linter ()
  (require 'envrc)
  (let ((go-backend 'lsp) (lsp-diagnostics-mode t) routed)
    (with-temp-buffer
      (setq major-mode 'go-mode)
      (unwind-protect
          (cl-letf (((symbol-function 'require) (lambda (&rest _) t))
                    ((symbol-function 'executable-find)
                     (lambda (_)
                       (and (seq-some (lambda (path)
                                        (and path (equal (directory-file-name path) "/project/bin")))
                                      exec-path)
                            "/project/bin/golangci-lint")))
                    ((symbol-function 'lsp-diagnostics-mode)
                     (lambda (arg)
                       (setq lsp-diagnostics-mode (> arg 0))
                       (when (> arg 0) (push lsp-diagnostics-provider routed)))))
            (advice-add 'envrc--apply :after #'nh/emacs-envrc-updated)
            (envrc--apply (current-buffer) '(("PATH" . "/project/bin")))
            (should go-use-golangci-lint)
            (should (eq lsp-diagnostics-provider :none))
            (envrc--apply (current-buffer) '(("PATH" . "/project/no-tools")))
            (should-not go-use-golangci-lint)
            (should (eq lsp-diagnostics-provider :auto))
            (should (equal routed '(:auto :none))))
        (advice-remove 'envrc--apply #'nh/emacs-envrc-updated)))))
