section: screens
    nix-desktop:
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	xebia-macos:
		switchCorners = none
		switchCornerSize = 0
	nix-laptop:
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	xebia-macos:
		right = nix-desktop
	nix-desktop:
		right = nix-laptop
		left = xebia-macos
	nix-laptop:
		left = nix-desktop
end

section: options
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
end
