---
name: Check workstations

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix develop .#ci --command make format-check
      - run: nix develop .#ci --command make lint
      - run: nix develop .#ci --command make test
      - run: nix develop .#ci --command make secret-check
      - run: nix flake check --no-build --all-systems
      - run: nix develop .#ci --command make build-linux
