---
name: Check fleet

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  evaluate:
    name: evaluate ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nix-desktop
            runner: ubuntu-24.04
            attribute: checks.x86_64-linux.nix-desktop
          - name: prime-mini
            runner: ubuntu-24.04-arm
            attribute: checks.aarch64-linux.prime-mini
          - name: nix-mac
            runner: macos-15
            attribute: checks.aarch64-darwin.nix-mac
          - name: home-julian
            runner: macos-15
            attribute: checks.aarch64-darwin.home-julian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix eval --raw ".#${{ matrix.attribute }}.drvPath"
